#!/bin/sh

ROOTFS_FILE="rootfs.tar.bz2"

if [ -f ${ROOTFS_FILE} ]; then
    rm ${ROOTFS_FILE}
    sync
fi

# add .gitignore file to empty diretory
find . -name .git -prune -o -type d -empty -exec touch {}/.gitignore \;

# generate a rootfs.tar.bz2
fakeroot -- tar jcvf ${ROOTFS_FILE} *

